# Generated by Django 4.1.4 on 2022-12-22 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('tagline', models.CharField(default='no tagline', max_length=150)),
                ('image_url', models.CharField(default='no image', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Haiku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=False, max_length=50)),
                ('body', models.CharField(max_length=300)),
                ('created_on', models.DateField(default='date.today')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haikus', to='ephemera.user')),
            ],
        ),
    ]
