# Generated by Django 4.1.4 on 2022-12-31 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ephemera', '0002_alter_haiku_body_alter_haiku_created_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
