# Generated by Django 4.1.4 on 2023-01-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ephemera', '0005_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='author name', max_length=100)),
                ('body', models.TextField(default='classic haiku', max_length=500)),
                ('year', models.CharField(default='yyyy', max_length=20)),
            ],
        ),
    ]
