# Generated by Django 4.1.4 on 2023-01-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ephemera', '0006_classics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classics',
            new_name='Classic',
        ),
    ]
